version: "3.8"
services:
  protobuf:
    image: protobuf:mitsukuni
    build:
      context: .
    user: "${MYUID:-1000}:${MYGID:-1000}"
    volumes:
     - ./protos:/protos:ro
     - ./outputs:/outputs
