#!/usr/bin/env bash
csharp_out=""
includes=()
outs=()
args=()

for arg in $@; do
    case $arg in
        --csharp_out=*)
            csharp_out=${arg}
            shift
            ;;
        --grpc-csharp_out=*)
            csharp_out=${arg}
            shift
            ;;
        --*_out=*)
            outs+=(${arg})
            shift
            ;;
        -I*|--proto_path=*)
            includes+=(${arg})
            shift
            ;;
        *)
            args+=(${arg})
            ;;
    esac
done

if [ ${#includes[@]} -eq 0 ]; then
    # replicate protoc behavior
    includes+=("-I.")
fi

protoc_cmd="protoc ${includes[@]} ${outs[@]} ${args[@]}"
protoc_csharp_cmd="protoc-csharp ${includes[@]} ${csharp_out} ${args[@]}"

if [ ${csharp_out} ]; then
    ${protoc_csharp_cmd} && echo "Succeeded to generate your codes!" || exit 1
fi
if [ ${#outs[@]} -gt 0 ]; then
    exec ${protoc_cmd} && echo "Succeeded to generate your codes!"
fi
